### ISSUE TITLE
[TASK]: Início Site Estático

### ISSUE THREAD

**Issue by alsgu3rra** [onixcontent/dashboard-ui#1]
Crie um site estático com html, css, javascript e bootstrap.

## ☕ TO-DO

- [x] Estrutura de Pastas
- [x] Página Index
- [x] Página Criar Produto
- [x] Página Tabela de Produtos
- [x] Página Tabela de Operações
- [x] Ícone padrão para o navegador
- [x] Layout Padrão
- [x] Cabeçalho da Página
- [x] Barra Lateral
- [x] Barra Superior de Navegação
- [x] Conteúdo Principal
